target-version = "py310"

[tool.black]
target-version = ["py310"]
[tool.ruff]
select = ["E", "F"]
ignore = ["E501", "E741"]
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py", "*_test.py", "testing/python/*.py"]
testpaths = [
    "tests",
]